[package]
name = "oracle-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eth2_ssz_derive = "0.3.0"
ethereum_ssz = "0.5.2"
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"
